### PR TITLE
LAS 413

### PR DESCRIPTION
**Pull request by thefenriswolf**
I know hubertbanas is better at this but I just had some sparetime.

Anyway, as the Shownotes provide two different Links for the Desktop App Pick (Launchpad and Github)
I chose the Github link, as it provides install instructions and links to multiple repos as well as the PPA from Launchpad. I hope this is OK!

### CODE REVIEW

**Comment by hubertbanas** [comment]
@thefenriswolf not sure what you did there with all of these (5) "updating my fork" but your LAS 413 data looks good.

@MichaelTunnell are you planning to merge this?

**Comment by MichaelTunnell** [comment]
@hubertbanas the first 5 points of the commits were just @thefenriswolf updating his fork with the previous merges you did so that what he sent as a PR was up to date. I'm not sure why GitHub recognized this as changes but meh whatever. :)

**Comment by hubertbanas** [comment]
I get it ... I guess my workflow is different and doesn't spam the git history

ex.
```
git fetch upstream
git rebase upstream/master
```
Work on your stuff
```
git push origin 
```
Open PR using github

Anyhow ... I updated the temporary testing location with the latest changes https://www.jupiterbroadcasting.tk/laspicks/

**Comment by thefenriswolf** [comment]
@MichaelTunnell I just followed your guide on how to keep my repo in sync. Not sure why Github put these merges into the PR too.
Maybe I did it wrong, I'll try to use the CLI next time

**Comment by MichaelTunnell** [comment]
@hubertbanas thanks

@thefenriswolf that's just fine with me, I don't really care that it is being listed, shows you're keeping up to date consistently and I like that. :)

**Comment by hubertbanas** [comment]
Created wiki page on how to keep repo in sync using CLI
https://github.com/MichaelTunnell/las-picks/wiki/How-to-keep-forked-repo-in-sync-using-command-line

**Pull request merged**
