### PR TITLE
Added all shows till 405

### LINKED ISSUE #26: push latest data from server to GitHub
The data file on the server is out of date to the GitHub repo so I need to push the latest content to the GitHub repo to keep it in sync.

### PR DESCRIPTION
**Pull request by htesligte**
Also merged changes from the live website back into the code, so this should fix #26

### CODE REVIEW

**Comment by TimoDJatomika** [comment]
awsome !

**Comment by FolkyHobbit** [comment]
awsome, I was thinking of updating it, but it seems you have already done the work ;).

**Comment by TimoDJatomika** [comment]
@FolkyHobbit no problem. Thanks for the work. @MichaelTunnell just has to accept the pull request

**Comment by MichaelTunnell** [comment]
This is a great help! Thank you for contributing to this effort. I have been incredibly swamped lately and just haven't had time to keep up with it so I very much appreciate it.

> Also merged changes from the live website back into the code, so this should fix #26

This is not accurate because when I was referring to moving stuff from the site to the github, I wasn't referring to pick data, I was referring to new code. This means that the new code is only accessible by my at this point and I need to put it on here so everyone can have it.

@TimoDJatomika it's not as simple as just accepting the request as there is a lot of code on the site that isn't here, not just data.

I do appreciate the efforts to update the site from everyone who has contributed with the latest pull requests. I will try to get the data and the code conflicts merged this weekend. Thanks again!

**Comment by MichaelTunnell** [comment]
I have merged this request, there is still more to do in order to put it live on the site but thank you very much for contributing to this repo!

**Comment by htesligte** [comment]
@MichaelTunnell If necessary, you could also upload the code from the server somewhere, or push it to another branch. I, or someone else from the community could try to merge it.

**Comment by MichaelTunnell** [comment]
@htesligte thank you very much for the offer but that won't be necessary. I already started the merging process and am almost finished with it. :)

I also decided to restructure the contributions page on the website so it flowed better with the new contributors being added such as yourself.

There were a couple of issues with your PR but nothing big, missing syntax and just some data conflicts for episodes in the 370s that I neglected to merge previously.

Anyway, thanks again. This saved me a TON of time and I appreciate that immensely. I will have to updates done shortly for the live site and then I will push the new code to this repo right after.

**Comment by MichaelTunnell** [comment]
Everything is now up to date and sync'd with GitHub repo and the live site! 

;) Thanks again!

**Pull request merged**
