### PR TITLE
Add android pick to episode 427; Add Episode 428 & 429

### PR DESCRIPTION
**Pull request by hubertbanas**
We should keep the data consistent even though this episode didn't have a pick.

Available at: https://www.jupiterbroadcasting.tk/laspicks/

### CODE REVIEW

**Comment by MichaelTunnell** [comment]
During this year there have been 29 episodes so far with only 8 of them having Android picks. I'm considering removing the display since there have been so few.

The previous reason I wanted to always include Android picks was because they were more common in 2015 with 28 out of 52. 2014 is even more populated with 34 out of 52.

The pattern though implies that the Android picks will be very seldom now and perhaps in 2017 almost non-existent.

What do you think?

**Comment by hubertbanas** [comment]
I would like to keep including Android pics for the remaining of 2016 and possibly drop it starting January 2017. I also think we should keep the navigation and maybe put "Archive" stamp on it once we stop including Android all together.

**Comment by MichaelTunnell** [comment]
> I also think we should keep the navigation and maybe put "Archive" stamp on it once we stop including Android all together.

I'm not wanting to stop keeping track of Android picks. I'm suggesting that when there isn't actually a pick we just ignore it and when there is we include it. Similar to how I setup the Distros page.

**Comment by hubertbanas** [comment]
Agreed.

**Pull request merged**
